### ISSUE TITLE
Can we use asyncio.as_completed instead of asyncio.gather in the _process_multiple_tasks function?

### ISSUE THREAD

**Issue by asrlhhh** [Evil0ctal/Fast-Powerful-Whisper-AI-Services-API#1]
首先，非常感谢你创建这个开源项目！通过阅读你的代码，我学到了很多关于高效hosting ML model的知识。在我学习代码的核心部分，特别是 task_processor 文件时，我注意到 _process_multiple_tasks 在开始时生成了一个任务的 future 列表，但它会等待所有任务完成后才将它们统一一起更新到cleanup和callback queue中

想请教下这里面用gather而不用as_completed的原因是什么？是否可以让每个任务/future 单独运行并完成，然后更新queue并释放该任务的资源？我之所以有这个疑问，是因为每个任务的处理时间取决于音频的时长。因此每批次中最长的音频会延迟所有其他较短音频的转录结果的交付？

如果我对代码有任何误解，还请指正！

**Comment by Evil0ctal** [comment]
The suggestion you mentioned is very good. Using `asyncio.as_completed` can indeed optimize the task processing process. The reason why `asyncio.gather` is used in the current code is that it is convenient to wait for a group of tasks to complete and handle exceptions uniformly. You can fork a code and update this issue and test whether there is a problem. If possible, you can submit a PR.

**Comment by Evil0ctal** [comment]
> The suggestion you mentioned is very good. Using `asyncio.as_completed` can indeed optimize the task processing process. The reason why `asyncio.gather` is used in the current code is that it is convenient to wait for a group of tasks to complete and handle exceptions uniformly. You can fork a code and update this issue and test whether there is a problem. If possible, you can submit a PR.

However, using `asyncio.gather` will allow batch processing of tasks. In scenarios involving multiple GPUs, it may be better to use `asyncio.gather` to process multiple tasks simultaneously, but the specific effect still needs further testing.

**Comment by asrlhhh** [comment]
Thanks for the response and explanation. I will try implementing that and keep you updated!

**Comment by JackLo111** [comment]
Sorry, when i run the code as instuction. The following message is printed on the screen: Invalid argument(s) 'pool_size','max_overflow','pool_timeout' sent to create_engine(), using configuration SQLiteDialect_aiosqlite/NullPool/Engine.  Please check that the keyword arguments are appropriate for this combination of components.
