### ISSUE TITLE
[Bug] Case sensitivity issue with TaskPriority enum values

### ISSUE THREAD

**Issue by alonegg** [Evil0ctal/Fast-Powerful-Whisper-AI-Services-API#3]
Description:
When retrieving task results via the API, I encountered an error related to case sensitivity of the TaskPriority enum values.

**Bug Description**
The system throws an error when the taskpriority value is lowercase 'normal', only accepting uppercase 'NORMAL'.

Steps to Reproduce

Call the /api/whisper/tasks/result API endpoint
Use task_id = 2 ( 1 was the same error)
Receive 500 error due to enum case mismatch

Expected Behavior
Either:

The system should handle case-insensitive enum values, or
The documentation should clearly specify that uppercase values are required

Current Behavior
The system only accepts uppercase enum values (LOW, NORMAL, HIGH) and fails with lowercase input.
Environment

API Endpoint: http://myserver-sorry to hide//
Time of occurrence: 2024-12-18 11:18:25

Additional Context
This might affect other parts of the system where enum values are used. Consider making the enum handling case-insensitive or adding validation/documentation to prevent similar issues.

Would you like me to modify any part of this issue template?

**Error Message**
```json
{
    "detail": {
        "code": 500,
        "message": "An unexpected error occurred while retrieving the task result: 'normal' is not among the defined enum values. Enum name: taskpriority. Possible values: LOW, NORMAL, HIGH",
        "time": "2024-12-18 11:18:25",
        "router": "http://myserver-sorry to hide/api/whisper/tasks/result?task_id=2",
        "params": {
            "task_id": "2"
        }
    }
}

**Comment by Evil0ctal** [comment]
Hi, after I reproduce this issue I found out this only happened when use SQLite as database, it will be working fine for MySQL, but I will try to fix it and make sure it will work for both databases, and this issue template looks great, I will update here once this issue gets fixed:)

**Comment by Evil0ctal** [comment]
### Problem Cause

In MySQL, the `Enum` type can be directly mapped to the native `ENUM` data type in the database. However, SQLite does not have a native `ENUM` type. Instead, it maps the `Enum` type to a `CHECK` constraint or stores it as a `TEXT` type. Therefore, using the native SQLAlchemy `Enum` type may cause issues when working with SQLite.

- **MySQL**: Natively supports the `ENUM` data type.
- **SQLite**: Does not natively support the `ENUM` data type.

### Solution

By refactoring the code to consistently use lowercase values for passing and storing all enumeration values, the system now works correctly with both MySQL and SQLite.

**Comment by alonegg** [comment]
Thank you for your quick response and resolution on the issue. I really appreciate your efficient support!

**Comment by Evil0ctal** [comment]
You are welcome, and merry early Christmas 🎄
